CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y

CONFIG_PMW3360=y
CONFIG_PMW3360_CPI=1600
CONFIG_PMW3360_CPI_DIVIDOR=1
CONFIG_PMW3360_SNIPE_CPI=800
CONFIG_PMW3360_SNIPE_CPI_DIVIDOR=1
CONFIG_PMW3360_ORIENTATION_90=y
CONFIG_PMW3360_INVERT_Y=y
CONFIG_PMW3360_RUN_DOWNSHIFT_TIME_MS=2550
CONFIG_PMW3360_REST1_DOWNSHIFT_TIME_MS=81600
CONFIG_PMW3360_REST2_DOWNSHIFT_TIME_MS=816000
