CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9
CONFIG_BT_PERIPHERAL_PREF_LATENCY=16
CONFIG_BT_BUF_ACL_TX_COUNT=32
CONFIG_BT_L2CAP_TX_BUF_COUNT=32

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 启用键盘RGB功能
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
# CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
# CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3


# 1. 양쪽 키보드 간의 통신 간격(Connection Interval)을 최대로 압축
# 데이터를 7.5ms~15ms 주기로 칼같이 주고받게 만들어 신호 지연으로 인한 커서 밀림을 원천 차단합니다.
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12

# 2. 블루투스 통신 신호 세기 강화
# 전파 간섭으로 인해 패킷이 재전송되면서 클릭 시 커서가 튀는 현상을 막아줍니다.
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
