# CONFIG_BT_LL_SW_LLCP_LEGACY=y

# CONFIG_BT_PERIPHERAL_PREF_MAX_INT=9
# CONFIG_BT_PERIPHERAL_PREF_LATENCY=16
# CONFIG_BT_BUF_ACL_TX_COUNT=32
# CONFIG_BT_L2CAP_TX_BUF_COUNT=32

CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

CONFIG_BT_CTLR_PHY_2M=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
CONFIG_ZMK_KEYBOARD_NAME="KMS-Charydbis"

# 启用键盘RGB功能
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_WS2812_STRIP=n
CONFIG_LED_STRIP=n
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3

# 旋钮配置
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# MOUSE
CONFIG_ZMK_POINTING=y

# Enable 32kHz crystal
# CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y
# CONFIG_CLOCK_CONTROL_NRF_K32SRC_30PPM=y

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=7
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7

# 1. 전역 슬립 모드 기능 자체를 활성화 (기본값은 n)
CONFIG_ZMK_SLEEP=n

# 2. [선택] 일반 유휴(Idle) 상태 진입 시간 (30,000ms = 30초)
# 30초 동안 타이핑이 없으면 LED를 끄거나 출력을 살짝 낮춰 전력을 아낍니다.
CONFIG_ZMK_IDLE_TIMEOUT=60000

# 3. [선택] 깊은 잠(Deep Sleep) 진입 시간 (900,000ms = 15분)
# 15분 동안 아무 움직임이 없으면 블루투스 송수신을 완전히 끄고 칩셋이 기절합니다.
# (팁: 너무 자주 잠드는 게 싫다면 이 수치를 조정하면 됩니다.)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
