name: Firmware Build

on:
  push:
    paths-ignore:
      - "keymap/**"
  pull_request:
  workflow_dispatch:

jobs:
  charybdis:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0
    with:
      build_matrix_path: builds/charybdis.yaml
      archive_name: charybdis-firmware

  senyatyl:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0
    with:
      build_matrix_path: builds/senyatyl.yaml
      archive_name: senyatyl-firmware
