name: Keymap Artwork

on:
  push:
    paths:
      - "config/**/*.keymap"
      - "config/**/*.dtsi"
      - "config/**/*.json"
      - "keymap_drawer.config.yaml"
  workflow_dispatch:

jobs:
  render:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      output_folder: "keymap"
